# application.yaml

server:
  port: 8080  # 配置服务器端口
  servlet:
    context-path: / # 配置应用上下文路径

spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://10.0.0.190:3306/your_database_name?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: rootrootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10 # 配置连接池最大连接数
      minimum-idle: 5  # 配置连接池最小空闲连接数
  # Redis 配置
  data:
    redis:
      host: 10.0.0.190  # Redis 主机地址
      port: 6379       # Redis 端口
      password: ""      # Redis 密码（如果没有设置密码可以为空）
      timeout: 2000     # 连接超时时间（毫秒）
      jedis:
        pool:
          max-active: 10 # Redis 连接池最大连接数
          max-idle: 5    # Redis 连接池最大空闲连接数
          min-idle: 1    # Redis 连接池最小空闲连接数
          max-wait: 10000 # Redis 连接池最大等待时间（毫秒）

  # RabbitMQ 配置
  rabbitmq:
    host: 10.0.0.190  # RabbitMQ 主机地址
    port: 5672       # RabbitMQ 端口
    username: guest   # RabbitMQ 用户名
    password: rootrootroot   # RabbitMQ 密码
    virtual-host: /   # RabbitMQ 虚拟主机
    listener:
      simple:
        concurrency: 3  # 配置监听的线程数
        max-concurrency: 10  # 配置最大线程数

  # 其他配置
  application:
    name: your-application-name # 设置应用的名称
# MyBatis 配置
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml  # MyBatis 映射文件路径
  type-aliases-package: cc.nireus.simple.model  # 指定 MyBatis 别名对应的类包路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 配置 MyBatis 日志输出
logging:
  level:
    root: INFO  # 配置日志级别
    org.springframework: INFO  # 设置 Spring 框架的日志级别
    com.example: DEBUG  # 设置自定义包下的日志级别

